# Generated by Django 2.1.7 on 2019-03-29 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('literary_genre', models.SmallIntegerField(choices=[(1, 'Fantasy'), (2, 'Westerns'), (3, 'Romance'), (4, 'Thriller'), (5, 'Criminal'), (6, 'Biography'), (7, "Children's books"), (8, 'Non-fiction'), (9, 'Sci-fi'), (10, 'Novels')], default=None)),
                ('isbn', models.CharField(max_length=40, unique=True)),
                ('publisher', models.CharField(max_length=200)),
                ('synopsis', models.CharField(default=None, max_length=9000)),
                ('book_cover', models.ImageField(null=True, upload_to='media/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='BookRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(choices=[(1, 'No way'), (2, 'Weak'), (3, 'Nearly'), (4, 'Interesting'), (5, 'Good'), (6, 'Very good'), (7, "I can't tear myself away"), (8, 'Masterpiece')], default=None)),
                ('comment', models.TextField(default=None, max_length=5000)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mybooks.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'To read'), (2, 'In progress'), (3, 'Done')], default=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mybooks.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
