# Generated by Django 2.1.7 on 2019-03-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='literary_genre',
            field=models.SmallIntegerField(choices=[(0, 'Unknown'), (1, 'Fantasy'), (2, 'Westerns'), (3, 'Romance'), (4, 'Thriller'), (5, 'Criminal'), (6, 'Biography'), (7, "Children's books"), (8, 'Non-fiction'), (9, 'Sci-fi'), (10, 'Novels')], default=0),
        ),
    ]
