# Generated by Django 2.1.7 on 2019-03-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybooks', '0003_auto_20190329_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.CharField(max_length=9000, null=True),
        ),
    ]
