# Generated by Django 2.1.7 on 2019-03-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybooks', '0003_auto_20190312_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='media/covers/'),
        ),
    ]
