# Generated by Django 2.1.7 on 2019-03-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybooks', '0004_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='literary_genre',
            field=models.SmallIntegerField(choices=[(1, 'Fantasy'), (2, 'Westerns'), (3, 'Romance'), (4, 'Thriller'), (5, 'Criminal'), (6, 'Biography'), (7, "Children's books"), (8, 'Non-fiction'), (9, 'Sci-fi'), (10, 'Novels')], default=None),
        ),
    ]
