# Generated by Django 2.1.7 on 2019-03-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybooks', '0004_book_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='default.jpg', upload_to='covers/'),
        ),
    ]
