# Generated by Django 2.1.7 on 2019-03-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybooks', '0005_auto_20190316_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(default='default.jpg', upload_to='media/covers/'),
        ),
    ]
