# Generated by Django 2.1.7 on 2019-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mybooks', '0006_auto_20190316_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(null=True, upload_to='media/covers/'),
        ),
    ]
