# Generated by Django 2.1.7 on 2019-03-17 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mybooks', '0006_auto_20190317_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'To read'), (2, 'In progress'), (3, 'Done')], default=None)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mybooks.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mybooks.Book'),
        ),
        migrations.AlterField(
            model_name='bookrate',
            name='rate',
            field=models.FloatField(choices=[('1', 'No way'), ('2', 'Weak'), ('3', 'Nearly'), ('4', 'Interesting'), ('5', 'Good'), ('6', 'Very good'), ('7', "I can't tear myself away"), ('8', 'Masterpiece')], default=None),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
