# Generated by Django 2.1.7 on 2019-03-17 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Mybooks', '0007_auto_20190317_0952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='BookComments',
        ),
    ]
